---
title: "Fennoscandian lakes"
author: "Camille Crapart"
date: "19 1 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library}
library(DBI)
library(sf)
library(dplyr)
library(gimms)
library(raster)

library(ncdf4)
library(rgdal)

library(stringr)
library(ggplot2)
library(tibble)

library(cowplot)
library(spdep)

source("f_plotspatial.R")
```

# Lake Catchments

The catchment and TOC data are stored on the PostgreSQL database ecco_biwa, accessed through Rstudio using the st_read function (sf package @Pebesma2021) and the dplyr package @Wickhman2021. 


```{r load-data}
con <- dbConnect(RPostgreSQL::PostgreSQL(),user = "camille.crapart", password = "camille",host = "vm-srv-wallace.vm.ntnu.no", dbname = "nofa")

all_catchment_area <- tbl(con,sql("SELECT ebint,catchment_area_km2 FROM catchments.lake_catchments")) %>% tbl_df()

all_catchment_area <- arrange(all_catchment_area, catchment_area_km2)
all_catchment_area$cumsum_area <- cumsum(all_catchment_area$catchment_area_km2)

closest<-function(xv,sv){
xv[which(abs(xv-sv)==min(abs(xv-sv)))] }

x <- closest(all_catchment_area$cumsum_area,0.05 * max(all_catchment_area$cumsum_area))

y <- which(all_catchment_area$cumsum_area == x)

z <- all_catchment_area$catchment_area_km2[y]

fen.catchment.poly <- st_read(con,query = paste("SELECT ebint,geom, catchment_area_km2 FROM catchments.lake_catchments WHERE catchment_area_km2 >",z, sep = " "))

saveRDS(fen.catchment.poly,"fen.catchment.poly.Rdata")

ggplot()+geom_sf(data=fen.catchment.poly, aes(fill=ebint,col=ebint))
ggsave(filename = "catchments.png",dpi = "retina", width = 30, height = 90, units = "cm")

```
```{r ndvi}
ndvi.1994 <- downloadGimms(x= 1994,y=1994,dsn = "Rasters")
ndvi.max <- monthlyComposite(ndvi.1994,monthlyIndices(ndvi.1994))
saveRDS(ndvi.max,"ndvi.max.Rdata")
ndvi.max <- readRDS("ndvi.max.Rdata")
summer.mean <- raster::stack(ndvi.max[[6]],ndvi.max[[7]],ndvi.max[[8]]) %>% mean()
summer.scan <- reclassify(summer.mean, cbind(-Inf, 0, NA), right=FALSE)

## Catchment extraction and transformation
fen.ndvi <- raster::extract(summer.scan,fen.catchment.poly, fun = mean, df = T, sp = T)
saveRDS(fen.ndvi,"fen.ndvi.Rdata")

```
```{r extract-runoff}
runoff.file.60s <- "Rasters/mrros_EUR-11_NCC-NorESM1-M_historical_r1i1p1_DMI-HIRHAM5_v3_mon_196101-197012.nc"
runoff.file.70s <- "Rasters/mrros_EUR-11_NCC-NorESM1-M_historical_r1i1p1_DMI-HIRHAM5_v3_mon_197101-198012.nc"
runoff.file.80s <- "Rasters/mrros_EUR-11_NCC-NorESM1-M_historical_r1i1p1_DMI-HIRHAM5_v3_mon_198101-199012.nc"


# get coordinates
runoff.nc <- nc_open(runoff.file.60s)
runoff.info <- GDALinfo(runoff.nc)
attr.runoff <- attr(runoff.info,"mdata")

rot.info <- attr.runoff[grep("^rotated",attr(runoff.info,"mdata"))]
coord <- sapply(rot.info, FUN = function(x) {
  unlist(str_split(x, pattern = "="))[2]})
coord.num<- round(as.numeric(coord[2:3]),2)

y <- coord.num[1]
x <- coord.num[2]

target.crs <- paste0("+proj=ob_tran +o_proj=longlat +o_lon_p=" , 
                     x, " +o_lat_p=", y, 
                     " +lon_0=180 +to_meter=0.0174532925199433")

# 60s
runoff.60.stack <- stack(runoff.file.60s, varname = "mrros")
runoff.60.mean  <- mean(runoff.60.stack)

projection(runoff.60.mean) <- CRS("EPSG:4326")
runoff.60.rotated <- projectRaster(runoff.60.mean,crs = target.crs)
runoff.60.wgs84 <- runoff.60.rotated
projection(runoff.60.wgs84) <- CRS("EPSG:4326")

runoff.60 <- raster::extract(runoff.60.wgs84,fen.catchment.poly, fun = mean, df = T, sp = T)
names(runoff.60) <- c("ebint", "area_km2","runoff_60")
saveRDS(runoff.60,"runoff.60.Rdata")

# 70s
runoff.70.stack <- stack(runoff.file.70s, varname = "mrros")
runoff.70.mean  <- mean(runoff.70.stack)

projection(runoff.70.mean) <- CRS("EPSG:4326")
runoff.70.rotated <- projectRaster(runoff.70.mean,crs = target.crs)
runoff.70.wgs84 <- runoff.70.rotated
projection(runoff.70.wgs84) <- CRS("EPSG:4326")

runoff.70 <- raster::extract(runoff.70.wgs84,fen.catchment.poly, fun = mean, df = T, sp = T)
names(runoff.70) <- c("ebint", "area_km2","runoff_70")
saveRDS(runoff.70,"runoff.70.Rdata")

# 80s
runoff.80.stack <- stack(runoff.file.80s, varname = "mrros")
runoff.80.mean  <- mean(runoff.80.stack)

projection(runoff.80.mean) <- CRS("EPSG:4326")
runoff.80.rotated <- projectRaster(runoff.80.mean,crs = target.crs)
runoff.80.wgs84 <- runoff.80.rotated
projection(runoff.80.wgs84) <- CRS("EPSG:4326")

runoff.80 <- raster::extract(runoff.80.wgs84,fen.catchment.poly, fun = mean, df = T, sp = T)
names(runoff.80) <- c("ebint", "area_km2","runoff_80")
saveRDS(runoff.80,"runoff.80.Rdata")

runoff.total <- merge(runoff.60,runoff.70[,c(1,3)], by = "ebint") %>% merge(runoff.80[,c(1,3)])
saveRDS(runoff.total,"runoff.total.Rdata")
```
```{r clc}
fen.catchment.poly <- readRDS("fen.catchment.poly.Rdata")
#fen.corine <- st_transform(fen.catchment.poly,CRS("EPSG:3035"))
#saveRDS(fen.corine,"fen.corine.Rdata")

fen.corine <- readRDS("fen.corine.Rdata")
corine <- raster::raster("Rasters/U2006_CLC2000_V2020_20u1.tif")

clc <- raster::extract(corine,fen.corine)
saveRDS(clc,"clc.fen.Rdata")

clc.tab <- sapply(clc, function(x) tabulate(x,45))
clc.tab.area <- clc.tab*prod(res(corine))
catchment.area <- colSums(clc.tab.area)
clc.tab.prop <- sweep(clc.tab.area,2,catchment.area, FUN = "/")
saveRDS(clc.tab.prop,"clc.tab.prop.Rdata")

clc.fen <- clc.tab.prop %>% t() %>% as.data.frame() 
rownames(clc.fen) <- fen.corine$ebint

clc.fen.bogs <- clc.fen %>% rownames_to_column(var="ebint") %>% dplyr::select(c("ebint","V36")) %>% setNames(c("ebint","bogs"))
clc.fen.forest <- dplyr::select(clc.fen,c("V23","V24","V25")) %>% rowSums() %>% as.data.frame() %>% setNames("forest") %>% rownames_to_column(var="ebint")

clc.fen.sum <- merge(clc.fen.bogs, clc.fen.forest, by = "ebint")
saveRDS(clc.fen.sum,"clc.fen.sum.Rdata")

clc.fen.sf <- merge(fen.catchment.poly,clc.fen.sum,by = "ebint")
saveRDS(clc.fen.sf,"clc.fen.sf.Rdata")

ggplot()+geom_sf(data = clc.fen.sf,aes(fill=bogs))

```

```{r gather-df}
fen.ndvi <- readRDS("fen.ndvi.Rdata")



runoff.total <- readRDS("runoff.total.Rdata")
clc.fen.sf <- readRDS("clc.fen.sf.Rdata")

fen.total <- merge(fen.ndvi,runoff.total, by = "ebint") %>% merge(clc.fen.sf,by = "ebint")
saveRDS(fen.total,"fen.total.Rdata")
fen.total <- readRDS("fen.total.Rdata")
ggplot()+geom_sf(data=fen.total,aes(fill=catchment_area_km2))
```
