---
title: "Test_model_NIVA"
author: "Camille Crapart"
date: "4 4 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r libraries}
library(readxl)
```

# Load data

```{r load-data}
niva <- read_xlsx("niva_selection.xlsx")
lake.poly <- st_read("C:/Users/raine/Documents/UiO/Paper_3/catchments_poly/lakes1000cat.shp")
lake.point <- st_read("C:/Users/raine/Documents/UiO/Paper_3/catchments_poly/lakes1000stations.shp")

ggplot(niva)+geom_point(aes(x = longitude, y = latitude, col = toc_2019))+
  scale_color_distiller(type = "seq", palette = 8, direction = -1)

### Summer NDVI 2015 -----
# http://poles.tpdc.ac.cn/en/data/9775f2b4-7370-4e5e-a537-3482c9a83d88/

# ndvi.2015 <- downloadGimms(x= 2015,y=2015,dsn = "NDVI")
# 
# ndvi.max.2015 <- monthlyComposite(ndvi.2015,monthlyIndices(ndvi.2015))
# saveRDS(ndvi.max.2015,"ndvi.max.2015.rds")
```

```{r NDVI}
ndvi.max.2015 <- readRDS("ndvi.max.2015.rds")

summer.scandinavia.2015 <- raster::crop(ndvi.max.2015,c(0,35,55,73))
summer.scan <- reclassify(summer.scandinavia.2015, cbind(-Inf, 0, NA), right=FALSE)

summer.mean.2015 <- raster::stack(summer.scan[[6]],summer.scan[[7]],summer.scan[[8]]) %>% mean()

summer.ndvi.2015 <- raster::extract(summer.mean.2015,lake.poly, fun = mean, df = T, sp = T, na.rm = T)
names(summer.ndvi.2015) <- c("station_id","ndvi")
summer.ndvi.2015$NDVI <- floor(summer.ndvi.2015$ndvi/10)/1000

saveRDS(summer.ndvi.2015, "NIVA_test/100lakes.summer.ndvi.2015.rds")
write.csv(summer.ndvi.2015,"NIVA_test/100lakes.summer.ndvi.2015.csv")
```


```{r niva-merged}

summer.ndvi.2015 <- readRDS("NIVA_test/100lakes.summer.ndvi.2015.rds")
niva.ndvi <- sp::merge(summer.ndvi.2015, select(st_drop_geometry(lake.point), c("statn_d", "sttn_cd", "longitd", "latitud")), by.x = "station_id", by.y = "statn_d")

niva_data <- niva.ndvi %>% merge(select(niva, c("station_id","station_code", "agriculture","forest","peat","nilu_ndep_2012_2016","nilu_sdep_2012_2016", "rr_2m_19", "toc_2019")), by.y = "station_code", by.x = "sttn_cd")
niva_data$Runoff <- niva_data$rr_2m_19 %>% as.numeric()
niva_data$logRunoff <- log(niva_data$Runoff)
niva_data$Bog <- niva_data$peat/100
niva_data$Forest <- niva_data$forest/100
niva_data$Arable <- niva_data$agriculture/100
niva_data$TNdep <- niva_data$nilu_ndep_2012_2016 * 10
niva_data$TSdep <- niva_data$nilu_sdep_2012_2016 * 100

saveRDS(niva_data,"NIVA_test/niva_data.rds")

ggplot(st_as_sf(niva_data))+geom_sf(aes(fill = toc_2019, col = toc_2019))+
  scale_color_distiller(palette = 8, aesthetics = c("fill","col"))

niva_final <- niva_data[-which(is.na(niva_data$Bog) == T),] 
niva_final <- niva_final[-which(is.na(niva_final$logRunoff) == T),]
niva_final <- niva_final[-which(is.na(niva_final$NDVI) == T), ]
#niva_final <- niva_final[-which(is.na(niva_final$Forest) == T), ]
#niva_final <- niva_final[-which(is.na(niva_final$Arable) == T), ]
niva_final <- niva_final[-which(is.na(niva_final$TNdep) == T), ]
# niva_final <- niva_final[-which(is.na(niva_final$TSdep) == T), ]

wr.sf.95 <- readRDS("WR/wr.sf.95.rds")
niva_final <- st_as_sf(niva_final) %>% st_transform(crs(wr.sf.95))
 
saveRDS(niva_final, "NIVA_test/niva_final.rds")
```

# Model

```{r niva-kmat}
niva_final <- readRDS("NIVA_test/niva_final.rds")
niva.kmat <- st_centroid(niva_final, of_largest_polygon = T) %>% knearneigh(k = 100) %>% knn2nb() %>% nb2listw()
saveRDS(niva.kmat,"NIVA_test/niva.kmat.rds")
```

```{r predict-toc}
sem.model <- readRDS("sem.fen.simple.Rdata")
niva_final <- readRDS("NIVA_test/niva_final.rds")
niva.kmat <- readRDS("NIVA_test/niva.kmat.rds")

fm <- logTOC~NDVI+logRunoff+Bog

niva_fit <- predict(sem.model, newdata = niva_final, niva.kmat)

niva_predict <- cbind(niva_final, niva_fit)
niva_predict$diffTOC <- exp(niva_predict$fit) - niva_predict$toc_2019

niva_predict$diffLogTOC <- log(niva_predict$toc_2019) - niva_predict$fit

ggplot(niva_predict) + geom_point(aes(x = log(toc_2019), y = fit))

saveRDS(niva_predict,"NIVA_test/niva_predict.rds")
```

```{r predict-toc-forest}
sem.forest.fen <- readRDS("sem.forest.fen.Rdata")
niva_final <- readRDS("NIVA_test/niva_final.rds")
niva.kmat <- readRDS("NIVA_test/niva.kmat.rds")

fm <- logTOC ~ Forest + logRunoff + Bog 
sem.forest.fen <- readRDS("sem.forest.fen.Rdata")
niva_fit <- predict(sem.forest.fen, niva_final, niva.kmat)

niva_predict_forest <- cbind(niva_final, niva_fit)
niva_predict_forest$diffTOC <- exp(niva_predict_forest$fit) - niva_predict_forest$toc_2019
niva_predict_forest$diffLogTOC <- log(niva_predict_forest$toc_2019) - niva_predict_forest$fit

ggplot(niva_predict_forest) + geom_point(aes(x = log(toc_2019), y = fit))

saveRDS(niva_predict_forest,"NIVA_test/niva_predict_forest.rds")

```

```{r plot-toc-predictions}
wr.sf.95 <- readRDS("WR/wr.sf.95.rds")
niva_predict <- readRDS("NIVA_test/niva_predict.rds")
nor <- st_read("Country_shapefile/norway.shp") %>% st_transform(st_crs(wr.sf.95))
mypal <- brewer.pal(9, name = "RdYlGn")
lims.toc <- c(min(c(niva_predict$toc_2019, exp(niva_predict$fit))), max((c(niva_predict$toc_2019, exp(niva_predict$fit)))))
  
diff.niva <- ggplot() +   geom_sf(data = nor, fill = "lightgray", col = "lightgray")+
  geom_sf(data = niva_predict, aes(fill = diffTOC, col = diffTOC)) + 
  scale_color_gradient2(low = mypal[9],high = mypal[1], mid = mypal[5], midpoint = 0, name = "Difference between\nobserved and predicted TOC\nwith NDVI, bogs, runoff (mg/L)", aesthetics = c("fill","col"))+
  labs(x = "", y = "")+
  theme_minimal(base_size = 6)+
  theme(legend.position = "bottom")
ggsave(plot = diff.niva, filename = "NIVA_test/diff.niva.png", dpi = "retina", width = 8, height = 10, units = "cm")
  
fitted.niva <- ggplot() +  geom_sf(data = nor, fill = "lightgray", col = "lightgray")+
  geom_sf(data = niva_predict, aes(fill = exp(fit), col = exp(fit))) + 
  scale_color_distiller(type = "seq", palette = 8, aesthetics = c("fill","col"), direction = 1, name = "Fitted TOC (mg/L)", limits = lims.toc)+
  labs(x = "", y = "")+
  theme_minimal(base_size = 6)+
  theme(legend.position = "bottom")

ggsave(plot = fitted.niva, filename =  "NIVA_test/fitted_niva.png",dpi = "retina", width = 8, height = 10, units = "cm")

obs.niva <- ggplot() + geom_sf(data = nor, fill = "lightgray", col = "lightgray") +
  geom_sf(data = niva_predict, aes(fill = toc_2019, col = toc_2019)) + 
  scale_color_distiller(type = "seq", palette = 8, aesthetics = c("fill","col"), direction = 1, name = "Sampled TOC (mg/L)", limits = lims.toc)+
  labs(x = "", y = "")+
  theme_minimal(base_size = 6)+
  theme(legend.position = "bottom")

ggsave(plot = obs.niva, filename = "NIVA_test/obs_niva.png",dpi = "retina", width = 8, height = 10, units = "cm", device = "png")
```

```{r plot-toc-predictions-forest}
niva_predict_forest <- readRDS("NIVA_test/niva_predict_forest.rds")
nor <- st_read("Country_shapefile/norway.shp") %>% st_transform(st_crs(wr.sf.95))
mypal <- brewer.pal(9, name = "RdYlGn")
lims.toc <- c(min(c(niva_predict_forest$toc_2019, exp(niva_predict_forest$fit))), max((c(niva_predict_forest$toc_2019, exp(niva_predict_forest$fit)))))

diff.niva.forest <- ggplot() + geom_sf(data = nor, fill = "lightgray", col = "lightgray") +
  geom_sf(data = niva_predict_forest, aes(fill = diffTOC, col = diffTOC)) + 
  scale_color_gradient2(low = mypal[9],high = mypal[1], mid = mypal[5], midpoint = 0, name = "Difference between\nobserved and predicted TOC\nwith Forest, bogs, runoff (mg/L)", aesthetics = c("fill","col"))+
  labs(x = "", y = "")+
  theme_minimal(base_size = 6)+
  theme(legend.position = "bottom")
ggsave(plot = diff.niva.forest, filename = "NIVA_test/diff.niva.forest.png", dpi = "retina", width = 8, height = 10, units = "cm")
  
fitted.niva.forest <- ggplot() +geom_sf(data = nor, fill = "lightgray", col = "lightgray") +
  geom_sf(data = niva_predict_forest, aes(fill = exp(fit), col = exp(fit))) + 
  scale_color_distiller(type = "seq", palette = 8, aesthetics = c("fill","col"), direction = 1, name = "Fitted TOC (mg/L)", limits = lims.toc)+
  labs(x = "", y = "")+
  theme_minimal(base_size = 6)+
  theme(legend.position = "bottom")

ggsave(plot = fitted.niva.forest, filename =  "NIVA_test/fitted.niva.forest.png",dpi = "retina", width = 8, height = 10, units = "cm")

obs.niva.forest <- ggplot() + geom_sf(data = nor, fill = "lightgray", col = "lightgray") +
  geom_sf(data = niva_predict_forest, aes(fill = toc_2019, col = toc_2019)) + 
  scale_color_distiller(type = "seq", palette = 8, aesthetics = c("fill","col"), direction = 1, name = "Sampled TOC (mg/L)", limits = lims.toc)+
  labs(x = "", y = "")+
  theme_minimal(base_size = 6)+
  theme(legend.position = "bottom")
ggsave(plot = obs.niva.forest, filename = "NIVA_test/obs.niva.forest.png",dpi = "retina", width = 8, height = 10, units = "cm", device = "png")
```